/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconOpenAi: typeof import('~icons/icon/open-ai')['default']
    IconPhone: typeof import('~icons/icon/phone')['default']
    IconProject: typeof import('~icons/icon/project')['default']
    IconQq: typeof import('~icons/icon/qq')['default']
    IconSend: typeof import('~icons/icon/send')['default']
    IconWeChat: typeof import('~icons/icon/we-chat')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
